version: "3"
services:
  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /media/usb/influxdb:/data
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb

  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana
